spring:
  h2:
    console:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:32768/test
      port: 32768
      database: test
  jpa:
    hibernate:
      ddl-auto: none
changelogs_package: edu.otus.spring03.changelogs
server:
  servlet:
    session:
      tracking-modes: cookie
